# Generated by Django 4.1.1 on 2022-10-16 17:21

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(unique=True)),
                ('views', models.PositiveIntegerField(blank=True, default=0)),
                ('time_for_read', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='preview_images/articles/', verbose_name='Превью картинка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField(verbose_name='Содержание')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge_base.article', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('TPC', 'Topic'), ('PRSBK', 'Phrasebook'), ('ART', 'Article'), ('HNDBK', 'Handbook'), ('QUIZ', 'Quiz')], db_index=True, default='ART', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='preview_images/categories/', verbose_name='Превью картинка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_category', to='knowledge_base.category', verbose_name='Предыдущая')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge_base.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_article', to='knowledge_base.article', verbose_name='Предыдущая'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('correct', models.BooleanField(default=False, verbose_name='Флаг правильности')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledge_base.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Тема статей',
                'verbose_name_plural': 'Темы статей',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.category',),
        ),
        migrations.CreateModel(
            name='HandbookCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Раздел справочника',
                'verbose_name_plural': 'Разделы справочника',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.category',),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
            ],
            options={
                'verbose_name': 'Статья справочника',
                'verbose_name_plural': 'Статьи справочника',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.article',),
        ),
        migrations.CreateModel(
            name='PhrasesArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Статья разговорника',
                'verbose_name_plural': 'Статьи разговорника',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.article',),
        ),
        migrations.CreateModel(
            name='PhrasesCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Раздел разговорника',
                'verbose_name_plural': 'Разделы разговорника',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.category',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.article',),
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Тема тестов',
                'verbose_name_plural': 'Темы тестов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.category',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
            ],
            options={
                'verbose_name': 'Топик',
                'verbose_name_plural': 'Топики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.article',),
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Темы топиков',
                'verbose_name_plural': 'Тема топиков',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_base.category',),
        ),
    ]
